### ISSUE TITLE
access for widget in usergroup

### ISSUE THREAD

**Issue by martin-git-kristensen** [waldhacker/ext-plausibleio#21]
# Bug Report

## Prerequisites

Can you reproduce the problem on TYPO3 v11.x - yes
Did you perform a cursory search to see if your bug or feature is already reported? -yes

## Description

If a usergroup dos not have access to the rootpage in backend - the widget cant be made on at user belonging to the usergroup.
The widget gets no data.

In the errorlog: Waldhacker\Plausibleio\Services\Exception\InvalidConfigurationException, code #1636815144, file /domain/docs/typo3conf/ext/plausibleio/Classes/Services/ConfigurationService.php, line 185: No plausible site id could be determined.

## Steps to Reproduce

1. user on a usergroup that dont have access to rootpage
2. user can see the widget but no data i available

Solution: in LocalConfiguration.php in the section 'plausibleio' add the 'siteId', 'baseUrl', and the 'apiKey' from the site file language settings.

**Expected behavior:** The widget is shown and data also

**Actual behavior:** [What actually happened] Errors because no data is availible

## Versions
TYPO3 Version: 11.5.31
PHP Version: 8.2.10
Plausibleio: 2.1.0

**Comment by waldhacker1** [comment]
Hi @martin-git-kristensen   
thanks for your contribution!
Please reopen your issue in the [new repository location](https://github.com/dreistromland/typo3-ext-plausibleio) if it is still relevant..

Thank you very much!
