### ISSUE TITLE
Possibility to filter by properties

### ISSUE THREAD

**Issue by RazielleS** [waldhacker/ext-plausibleio#22]
# Feature Request

**What is the use case for your feature?**
We would like to filter by properties, like it is already possible in the plausible interface.
![image](https://github.com/waldhacker/ext-plausibleio/assets/8451816/0434771c-9011-41cb-b889-b0424a0beb94)

This might be the intent of #20, but I do not know what is missing there.

**Do you already have a solution in mind?**
Each widget should have a filter button, which allows to select a property.
If possible, a shared filter between all widgets would be nice to have.

**Comment by waldhacker1** [comment]
Hi @RazielleS  
thanks for your contribution!
Please reopen your issue in the [new repository location](https://github.com/dreistromland/typo3-ext-plausibleio) if it is still relevant..

Thank you very much!
